# fly.toml app configuration file generated for xero-mcp-server on 2025-05-08T21:29:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "xero-mcp-server"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[processes]
  app = "node dist/index.js"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
